dictionary_file: "dictionary"

messages:
  responses:
    start: "Введите /start"
    already_start: "Я заработал"
    unknown_command: "Я не знаю такой команды"
    correct_answer: "Поздравляю, это правильный ответ"
    wrong_answer: "Упс, это неправильный ответ"
    the_correct_answer_was: "Правильный ответ был: "